### ISSUE TITLE
Soma Connect USB not working

### ISSUE THREAD

**Issue by stleusc** [Djelibeybi/aiosoma#211]
USB /list_devices
```
{"result":"success","version":"3.0.6","shades":[{"name":"Dining Room","mac":"xx:xx:xx:xx:xx:xx","type":"shade","count":"13961"}]}
```

RPi /list_devices
```
{"result":"success","version":"2.3.2","shades":[{"name":"Dining Room","mac":"xx:xx:xx:xx:xx:xx","type":"unknown","gen":"unknown"}]}
```

Gen and Type don't seem to be used anywhere. And my HW does not report useful data anyways as it seems.
To support Soma Connect USB it would help to create the device without Gen parameter.

Unsure if more changes are needed but I am happy to test once that change is implemented if that is possible.

Currently I am getting

```
Logger: custom_components.soma_connect.config_flow
Source: custom_components/soma_connect/config_flow.py:36
Integration: SOMA Connect ([documentation](https://github.com/Djelibeybi/hass-soma-connect), [issues](https://github.com/Djelibeybi/hass-soma-connect/issues))
First occurred: 3:45:43 PM (3 occurrences)
Last logged: 3:47:58 PM

Connection to SOMA Connect failed with RequestException
```

which I assume is due to the missing Gen parameter?!

**Comment by Djelibeybi** [comment]
Yeah, I don't have a SOMA Connect USB, so this plugin doesn't actually support it. Happy to accept pull requests if you want to add support, though.

**Comment by Djelibeybi** [comment]
I'm going to close this issue as I don't have plans to support the SOMA Connect USB.
